"use client";

import { useMemo, useState, useTransition } from "react";
import { saveScoreSheet } from "@/app/actions/results";
import { gradeFor, scoreTotal } from "@/lib/result-calculations";
import { EmptyTableRow } from "@/components/empty-state";
import { showToast } from "@/components/toast";

type StudentScore = { enrollmentId: string; name: string; admissionNumber: string | null; firstTest: number | null; secondTest: number | null; exam: number | null };

export default function ScoreSheet({ classId, termId, subjectId, subjectName, students }: { classId: number; termId: number; subjectId: number; subjectName: string; students: StudentScore[] }) {
  const [scores, setScores] = useState(students);
  const [pending, startTransition] = useTransition();
  const [message, setMessage] = useState("");
  const complete = useMemo(() => scores.filter((item) => item.firstTest !== null && item.secondTest !== null && item.exam !== null).length, [scores]);
  function update(index: number, field: "firstTest" | "secondTest" | "exam", raw: string) { setScores((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: raw === "" ? null : Number(raw) } : item)); }
  function keyDown(event: React.KeyboardEvent<HTMLInputElement>) { if (event.key !== "Enter") return; event.preventDefault(); const inputs = [...document.querySelectorAll<HTMLInputElement>(".score-input")]; inputs[inputs.indexOf(event.currentTarget) + 1]?.focus(); }
  return <section className="card"><div className="card-pad page-header" style={{ marginBottom: 0 }}><div><h3>{subjectName}</h3><p className="small muted">{complete} of {students.length} students complete</p></div><button className="button button-primary" aria-busy={pending} disabled={pending || !students.length} onClick={() => startTransition(async () => { setMessage(""); try { await saveScoreSheet({ classId, termId, subjectId, scores: scores.map(({ enrollmentId, firstTest, secondTest, exam }) => ({ enrollmentId, firstTest, secondTest, exam })) }); setMessage("Score sheet saved."); showToast({ type: "success", title: "Score sheet saved", message: `${complete} of ${students.length} student scores are complete.` }); } catch (error) { const text = error instanceof Error ? error.message : "Could not save scores."; setMessage(text); showToast({ type: "error", title: "Could not save scores", message: text }); } })}>{pending ? "Saving..." : "Save score sheet"}</button></div>{message && <div className={`notice ${message.includes("saved") ? "info" : "error"}`} style={{ margin: "0 20px 15px" }}>{message}</div>}<div className="table-wrap"><table className="table"><thead><tr><th>Student</th><th className="numeric">First test /20</th><th className="numeric">Second test /20</th><th className="numeric">Exam /60</th><th className="numeric">Total</th><th>Grade</th></tr></thead><tbody>{scores.map((student, index) => { const valid = student.firstTest !== null && student.secondTest !== null && student.exam !== null; const total = valid ? scoreTotal(student.firstTest!, student.secondTest!, student.exam!) : null; return <tr key={student.enrollmentId}><td><strong>{student.name}</strong><div className="small muted">{student.admissionNumber || "-"}</div></td><td className="numeric"><input aria-label={`${student.name} first test`} className="score-input" type="number" min="0" max="20" value={student.firstTest ?? ""} onKeyDown={keyDown} onChange={(event) => update(index, "firstTest", event.target.value)} /></td><td className="numeric"><input aria-label={`${student.name} second test`} className="score-input" type="number" min="0" max="20" value={student.secondTest ?? ""} onKeyDown={keyDown} onChange={(event) => update(index, "secondTest", event.target.value)} /></td><td className="numeric"><input aria-label={`${student.name} exam`} className="score-input" type="number" min="0" max="60" value={student.exam ?? ""} onKeyDown={keyDown} onChange={(event) => update(index, "exam", event.target.value)} /></td><td className="score-total">{total ?? "-"}</td><td>{total === null ? "-" : <span className="badge neutral">{gradeFor(total)}</span>}</td></tr>; })}{!scores.length && <EmptyTableRow colSpan={6} title="No students in this class" description="Enroll students in this class before entering scores." actionHref="/students" actionLabel="Manage students" />}</tbody></table></div></section>;
}
