import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { createPortalUser, updateSchoolSettings } from "@/app/actions/admin";
import { formatDate } from "@/lib/format";
import SubmitButton from "@/components/submit-button";

export default async function SettingsPage() {
  const user = await requireUser();
  if (user.role !== "OWNER") return <><header className="page-header"><div><h2>Settings</h2><p>School configuration and user management are available to owners.</p></div></header><div className="notice info">Ask your school owner to make configuration or account changes.</div></>;
  const [school, users] = await Promise.all([db.school.findUnique({ where: { id: user.schoolId } }), db.portalUser.findMany({ where: { schoolId: user.schoolId }, orderBy: [{ role: "asc" }, { displayName: "asc" }] })]);
  if (!school) return <div className="notice error">School settings have not been seeded.</div>;
  return <><header className="page-header"><div><h2>Settings</h2><p>Update the identity printed on report cards and manage the people who can access this school.</p></div></header><section className="grid two-column"><article className="card card-pad"><h3>School identity</h3><form action={updateSchoolSettings} className="form-grid"><div className="field"><label>School name</label><input className="input" name="name" defaultValue={school.name} required /></div><div className="field"><label>Short name</label><input className="input" name="shortName" defaultValue={school.shortName} required /></div><div className="field full"><label>Motto</label><input className="input" name="motto" defaultValue={school.motto ?? ""} /></div><div className="field full"><label>Address</label><textarea className="textarea" name="address" defaultValue={school.address ?? ""} /></div><div className="field"><label>Phone numbers</label><input className="input" name="phone" defaultValue={school.phone ?? ""} /></div><div className="field"><label>Principal’s name</label><input className="input" name="principalName" defaultValue={school.principalName ?? ""} /></div><div className="field full"><label>Logo URL</label><input className="input" type="url" name="logoUrl" defaultValue={school.logoUrl ?? ""} placeholder="Cloudinary secure URL" /></div><SubmitButton className="button button-primary field full" pendingLabel="Saving settings...">Save school settings</SubmitButton></form></article><aside><details className="panel" open><summary>Add administrator</summary><div className="panel-body"><form action={createPortalUser} className="form-grid"><div className="field full"><label>Full name</label><input className="input" name="displayName" required /></div><div className="field full"><label>Username</label><input className="input" name="username" required /></div><div className="field"><label>Role</label><select className="select" name="role"><option value="STAFF">Staff</option><option value="OWNER">Owner</option></select></div><div className="field"><label>Temporary password</label><input className="input" name="temporaryPassword" type="password" minLength={10} required /></div><SubmitButton className="button button-primary field full" pendingLabel="Creating account...">Create account</SubmitButton></form></div></details></aside></section><section className="card" style={{ marginTop: 20 }}><div className="card-pad"><h3>Administrators</h3></div><div className="table-wrap"><table className="table"><thead><tr><th>Name</th><th>Username</th><th>Role</th><th>Last login</th><th>Status</th></tr></thead><tbody>{users.map((account) => <tr key={account.id}><td>{account.displayName}</td><td>{account.username}</td><td><span className="badge neutral">{account.role}</span></td><td>{formatDate(account.lastLoginAt)}</td><td><span className={`badge ${account.isActive ? "success" : "danger"}`}>{account.isActive ? "Active" : "Disabled"}</span></td></tr>)}</tbody></table></div></section></>;
}
